os:
  editPreset: "nvim-remote"
customCommands:
  - key: "C"
    command: "~/.config/lazygit/commit-with-env.sh"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
gui:
  nerdFontsVersion: "3"
  theme:
    unstagedChangesColor:
      - "#f38ba8"
    selectedLineBgColor:
      - "#45475a"
    searchingActiveBorderColor:
      - "#fab387"
      - "bold"
    optionsTextColor:
      - "#89b4fa"
    inactiveBorderColor:
      - "#89b4fa"
    defaultFgColor:
      - "#cdd6f4"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#f2cdcd"
    activeBorderColor:
      - "#fab387"
      - "bold"
git:
  parseEmoji: true
