os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: "3"
  theme:
    unstagedChangesColor:
      - "#f38ba8"
    selectedLineBgColor:
      - "#45475a"
    searchingActiveBorderColor:
      - "#fab387"
      - "bold"
    optionsTextColor:
      - "#89b4fa"
    inactiveBorderColor:
      - "#89b4fa"
    defaultFgColor:
      - "#cdd6f4"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#f2cdcd"
    activeBorderColor:
      - "#fab387"
      - "bold"
